LUA
NGemity/RZEmulator pull request #4
Opened 2023-11-03 17:54 UTC by YoSiem

added possibility in get and set_value in the function argument to provide the name of the player from whom we want to receive or set value (just test if i can work with git xd)

2023-11-05 19:12 UTC, Xijezu requested changes
Fix the comments, also add necessary null check and type checks (is an argument really an integer? Check it before parsing!)

2023-11-05 19:12 UTC, Xijezu commented on Chihiro/src/Scripting/XLua.cpp
> +        m_pUnit = Player::FindPlayer(args[2].get<std::string>());
Don't overwrite m_pUnit ever!

2023-11-05 19:12 UTC, Xijezu commented on Chihiro/src/Scripting/XLua.cpp
> +    auto szKey = args[0].get<std::string>();
What happens if there are no arguments? null check missing

2023-11-05 19:12 UTC, Xijezu commented on Chihiro/src/Scripting/XLua.cpp
> +        m_pUnit = Player::FindPlayer(args[1].get<std::string>());
Here as well, don't overwrite m_pUnit!

2023-11-05 19:12 UTC, Xijezu commented on Chihiro/src/Scripting/XLua.cpp
> +    int count = (args.size() >= 5) ? args[4].get<__int64>() : 1;
What's __int64? We don't use it in the emu. Use int64_t instead

2023-11-05 19:12 UTC, Xijezu commented on Chihiro/src/Scripting/XLua.cpp
> +    int nLevel = (args.size() >= 7) ? args[6].get<int>() : 1;
Use int32_t

2023-11-07 18:15 UTC, YoSiem commented
fertigo

2025-05-29 19:24 UTC, closed without merging